### ISSUE TITLE
Cannot find run.bat or run.sh in .\venv folder

### ISSUE THREAD

**Issue by Magenta-6** [ouoertheo/silero-api-server#22]
I am wanting to run Silero-tts locally
Have worked through an install of the latest api, but cannot find a file [run.bat] or [run.sh] to execute.
See instructions from https://github.com/ouoertheo/silero-api-server

Starting Server
Enter the venv .\venv\scripts\Activate.ps1 Execute the included run.ps1 or run.sh You can access the API spec at http://localhost:8001/docs

All prior steps seemed to go flawlessly.
Not sure if this is a bug or if I am doing something wrong.  Any suggestions would be welcome.  
Thanks in advance - AND thanks for making this api available.  I'm really looking forward to using it outside of oobabooga!

**Comment by Camos101** [comment]
I think steps are being left out for whatever reason.
Why people don't make numbered steps with things this convoluted is beyond me...
1. Everyone isn't programmer minded and 2. Even if they are if a step or configuration is missing it helps no one...
How annoying...

**Comment by ouoertheo** [comment]
@Magenta-6 , sorry for the delay my friend. Virtual environments can be tricky for newcomers. The venv command was meant to be run from the root of the project, which is where the run scripts are also located. 
I'll get the readme improved to be more user friendly.

**Comment by ouoertheo** [comment]
@Magenta-6 , I updated the readme in #23. I learned how to package and publish to pypi so it's much more user friendly now. No scripts or anything. Let me know if anything comes up.

**Comment by Magenta-6** [comment]
@ouoertheo Thanks for your work. I deleted the branch and reinstalled. Everything installed nicely, the samples were generated, the checkpoint was downloaded and the route to the port came up perfectly in cmd. However when I try to open it in Google Chrome I am still getting the  same error message:

This site can’t be reached[::1] refused to connect.
Try:
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

I checked whether the port was blocked, by a firewall (No).
Interstingly the link to the (http://localhost:8001/docs#/) did show up on Chrome.

Stuck at the final hurdle again. 
![image](https://github.com/ouoertheo/silero-api-server/assets/116250074/39d79a52-e067-4b0a-8018-aef5d5009077)

Any suggestions would be welcome. Cheers!

**Comment by ouoertheo** [comment]
@Magenta-6 what URL are you trying to access? There's no direct GUI since this is just a REST API wrapper that can be plugged into other tools.

**Comment by Magenta-6** [comment]
Am trying to access http://0.0.0.0:8001/ through Chrome.
I don't know what a REST API is.  What other tools would you suggest?

**Comment by ouoertheo** [comment]
Ah yep. That's not gonna do anything. REST is essentially an HTTP request to a server without any HTML involved. There's more to it, but that's the gist. There's a bunch of material to read online about it. 

This is more of a local service/library/wrapper than a full end user app. I built this to serve up TTS to SillyTavern for the most part.

**Comment by Magenta-6** [comment]
So I can use it via Silly Tavern then.  Thanks for the explanation. Obviously I've been barking up the wrong tree.

**Comment by Magenta-6** [comment]
Post Script: Having struggled with this I found a video running through the installation and connecting it to SillyTavern.
Video is by a user: MoustacheAi - Kudos to you.
It is here:
https://www.youtube.com/watch?v=yRHbDbHPJMo 
@ouoertheo just a suggestion that it might be worth linking in the Readme.md to  - cheers!

**Comment by ouoertheo** [comment]
Hey, cool. I'm on TV >_<
Thanks @Magenta-6, you're awesome.

**Comment by ouoertheo** [comment]
Although... those instructions are not valid anymore with the newest release. I did fix a bug because of it!
